config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  resources :friends
  get 'home/index'
  get  'home/about'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  # def new
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <div class="mb-3">
    <%= form.label :first_name,class:"form-label" %>
    <%= form.text_field :first_name ,class:"form-control", placeholder:"abc"%>
    </div>

    <div class="mb-3">
      <%= form.label :last_name, style: "display: block",class:"form-label" %>
      <%= form.text_field :last_name,class:"form-control", placeholder:"xyz" %>
    </div>

    <div class="mb-3">
      <%= form.label :email, style: "display: block",class:"form-label" %>
      <%= form.text_field :email,class:"form-control", placeholder:"name@example.com" %>
    </div>

    <div class="mb-3">
      <%= form.label :phone, style: "display: block",class:"form-label" %>
      <%= form.text_field :phone,class:"form-control", placeholder:"541xxx651" %>
    </div>
    
    <div class="mb-3">
      <%= form.label :UserID, style: "display: block",class:"form-label" %>
      <%= form.text_field :user_id,class:"form-control", value:current_user.id %>
    </div>

    <div>
      <%= form.submit class:"btn btn-primary" %>
    </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <div class="card">
  <img src="app\assets\images\226-2261312_employee-clipart-employee-icon-employee-management-system-logo.png" class="card-img-top" alt="404 Not found">

  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">
      <p>
      <strong>First name:</strong>
      <%= friend.first_name %>
      </p>

      <p>
        <strong>Last name:</strong>
        <%= friend.last_name %>
      </p>

      <p>
        <strong>Email:</strong>
        <%= friend.email %>
      </p>

      <p>
        <strong>Phone:</strong>
        <%= friend.phone %>
      </p>
    </p>
    <%= link_to "Edit this friend", edit_friend_path(@friend),class:"btn btn-success" %> 
    <%= button_to "Destroy this friend", @friend, method: :delete,class:"btn btn-danger" %>
  </div>
</div>

</div>

</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend %> |
  <%= link_to "Back to friends list", friends_path %>
</div>

app/views/friends/index.html.erb
<h1>Friends List</h1>

<div id="friends">
<table class="table table-hover table-striped">
<thead class="table-dark">
    <tr>
      <th scope="col">First_name</th>
      <th scope="col">Last_name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
      <% @friends.each do |friend| %> 
      <tr>
      <td>
      <%= friend.first_name %>
      </td>
      <td>
      <%= friend.last_name %>
      </td>
      <td>
      <%= friend.email %>
      </td>
      <td>
      <%= friend.phone %>
      </td>
      <td>
      <%= link_to "Show this friend", friend %>
      </td>
      <td>
      <%= link_to "Edit this friend", edit_friend_path(friend) %>
      </td>
      </tr>
      <% end %>
  </tbody>
</table>

</div>
<% if user_signed_in? %>
  <%= link_to "New friend", new_friend_path,class:"btn btn-success" %>
<% end%>

app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/show.html.erb
<%= render @friend %>

<div>
  <%= link_to "Back to friends", friends_path,class:"btn btn-secondary" %>  
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg " style="background-color: Purple" data-bs-theme="dark">
  <div class="container-fluid">



    <%# <a class="navbar-brand" href="index">Friends List</a> %>
    <%= link_to "RemFri",root_path,class:"navbar-brand" %>



    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home",root_path,class:"nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "About Us",home_about_path,class:"nav-link active" %>
          <%# <a class="nav-link active" aria-current="page" href="home/about">About Us</a> %>
        </li>
        <li class="nav-item">
          <%= link_to "Show Friends",friends_path,class:"nav-link active" %>
        </li>
        <% if user_signed_in?%>
          <li class="nav-item">
            <%= link_to "Add New Friend",new_friend_path,class:"nav-link active" %>
          </li>
          <li class="nav-item">
          <%= link_to "Sign Out",destroy_user_session_path,method: :delete,class:"nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "Edit Profile",edit_user_registration_path,class:"nav-link active" %>
          </li>
        <% else %> 
          <li class="nav-item">
            <%= link_to "Sign Up",new_user_registration_path,class:"nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign In",new_user_session_path,class:"nav-link active" %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>
About Us
</h1>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-info" role="alert">
  <%= notice %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <title>Friends</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>
  <body>
  
    <%= render "home/header" %>
    <% if notice%>
    <br/>
      <%= render "layouts/alerts" %>
    <%end%>
    <h1> 
    <%= yield %>
    </h1>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>